package tech;

//plugs into parts to provide base material stats to help in description and generation. 
//also may be able to apply special effects.
public class material{
	
	//in kg/m^3
	private double density;
	
	//determines how fast material heats in joules/kelvin
	//steel at 1.23
	private double specificHeat;
	
	//max heat able to be absorbed before taking damage
	//hot==75%> melting point
	//overheat=100%>
	//onFire=150%
	//steel at 1510C
	private double meltingPoint;
	
	//ie steel
	private String materialName;
	
	//ohm*meters. use to determine damage done by electrical attacks by multiplying in size.
	//heat generated by (current of attack)^2*(conductivity*size)
	//when dealing with armour, use thickness instead of size.
	//steel(carbon) at 1.43*10^(-7)
	private double conductivity;
	
	public material(){
		
	}
	
	public material(double dens, double melt, double specific, double cond, String nameA){
		setDensity(dens);
		setMeltingPoint(melt);
		setSpecificHeat(specific);
		setConductivity(cond);
		setMaterialName(nameA);
	}

	public double getConductivity() {
		return conductivity;
	}

	public void setConductivity(double conductivity) {
		this.conductivity = conductivity;
	}

	public String getMaterialName() {
		return materialName;
	}

	public void setMaterialName(String materialName) {
		this.materialName = materialName;
	}

	public double getMeltingPoint() {
		return meltingPoint;
	}

	public void setMeltingPoint(double meltingPoint) {
		this.meltingPoint = meltingPoint;
	}

	public double getSpecificHeat() {
		return specificHeat;
	}

	public void setSpecificHeat(double specificHeat) {
		this.specificHeat = specificHeat;
	}

	public double getDensity() {
		return density;
	}

	public void setDensity(double density) {
		this.density = density;
	}
	
	public void printAll(){
		System.out.println("Material Name: "+getMaterialName());
		System.out.println("Density: "+getDensity());
		System.out.println("Specific Heat: "+getSpecificHeat());
		System.out.println("Melting Point: "+getMeltingPoint());
		System.out.println("Conductivity: "+getConductivity());
		
	}
	
	
}